services:
  backend:
    build: ./backend
    env_file:
      - ./backend/.env.prod
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis

  frontend:
    build: ./frontend
    env_file:
      - ./frontend/.env.prod
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

volumes:
  mongo-data:
  redis-data: