services:
  backend:
    build:
      context: .
    container_name: express-backend
    ports:
      - "5000:5000"
    env_file:
      - ./config/.env
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app
    command: npm run dev

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data/redis

  test:
    build:
      context: .
    container_name: express-test
    command: npm test
    env_file:
      - ./config/.env
    depends_on:
      - mongo
      - redis
    volumes:
      - .:/app

volumes:
  mongo-data:
  redis-data: