name: CI
on:
  push:
    branches:
      - feature/chat
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: build frontend
        run: |
          cd frontend
          npm ci
          npm run build

      - name: create .env
        run: |
           mkdir -p backend/config
            {
              echo "PORT=${{ secrets.PORT }}"
              echo "NODE_ENV=${{ secrets.NODE_ENV }}"
              echo "MONGODB_URL=${{ secrets.MONGODB_URL }}"
              echo "JWT_SECRET=${{ secrets.JWT_SECRET }}"
              echo "REDIS_HOST=${{ secrets.REDIS_HOST }}"
              echo "REDIS_PORT=${{ secrets.REDIS_PORT }}"
              echo "REACT_APP_BACKEND=${{ secrets.REACT_APP_BACKEND }}"
              echo "FRONTEND=${{ secrets.FRONTEND }}"
              echo "BACKEND=${{ secrets.BACKEND }}"
              echo "MONGO_URI_TEST=${{ secrets.MONGO_URI_TEST }}"
              echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}"
            } > backend/config/.env
      - name: Build backend
        run: |
          cd backend
          docker compose build
     
      - name: Run Backend test
        run: |
          cd backend
          docker compose up -d
          docker compose ps
          docker compose down