name: CI
on:
  push:
    branches:
      - deploy-test
      - feature/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: build frontend
        run: |
          cd frontend
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" > .env.dev

      - name: create .env
        run: |
           mkdir -p backend/config
           {
              echo "PORT=${{ secrets.PORT }}"
              echo "NODE_ENV=${{ secrets.NODE_ENV }}"
              echo "MONGODB_URL=${{ secrets.MONGODB_URL }}"
              echo "JWT_SECRET=${{ secrets.JWT_SECRET }}"
              echo "REDIS_HOST=${{ secrets.REDIS_HOST }}"
              echo "REDIS_PORT=${{ secrets.REDIS_PORT }}"
              echo "FRONTEND=${{ secrets.FRONTEND }}"
              echo "MONGO_URI_TEST=${{ secrets.MONGO_URI_TEST }}"
              echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}"
           } > backend/config/.env.dev
      - name: Build containers
        run: |
          docker compose -f docker-compose.dev.yaml build
     
      - name: Run Backend test
        run: |
          docker compose -f docker-compose.dev.yaml up -d
          sleep 10
          docker compose -f docker-compose.dev.yaml ps
          docker compose -f docker-compose.dev.yaml down